name: CMake

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure project
        working-directory: ./
        run: cmake -S ./ -B ./build

      - name: Build project
        working-directory: ./
        run: cmake --build ./build

  build_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure project
        working-directory: ./
        run: cmake -S ./ -B ./build

      - name: Build project
        working-directory: ./
        run: cmake --build ./build

  build_macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure project
        working-directory: ./
        run: cmake -S ./ -B ./build

      - name: Build project
        working-directory: ./
        run: cmake --build ./build